### ISSUE TITLE
Create Models for Janya and Melakarta based on DB schema

### ISSUE THREAD

**Issue by thadc23** [badesiru/Raga#1]
Use the `rails` command line interface to create model objects for both Janya and Melakarta.
Be sure to associate the models so the foreign key relationships work.

[Help is here](https://guides.rubyonrails.org/getting_started.html#generating-a-model)

**Comment by badesiru** [comment]
I added DB models Melakarta and Janya and ran DB migrate. It kept giving me errors about the primary key, so we took that part out.

**Comment by thadc23** [comment]
Rails will automatically put in a primary key for you called `id`.  I think it is fine to leave it the way you have it.
